include_guard(GLOBAL)


include_project_module(dependencies/Testing)
include_project_module(dependencies/Benchmarking)
include_project_module(dependencies/Coverage)
include_project_module(dependencies/Formatting)
